# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello-world.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hello-world.proto',
  package='hello_world',
  syntax='proto3',
  serialized_pb=_b('\n\x11hello-world.proto\x12\x0bhello_world\"%\n\x11HelloWorldRequest\x12\x10\n\x08greeting\x18\x01 \x01(\t\"\"\n\x12HelloWorldResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2`\n\x11HelloWorldGreeter\x12K\n\x08SayHello\x12\x1e.hello_world.HelloWorldRequest\x1a\x1f.hello_world.HelloWorldResponseb\x06proto3')
)




_HELLOWORLDREQUEST = _descriptor.Descriptor(
  name='HelloWorldRequest',
  full_name='hello_world.HelloWorldRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='greeting', full_name='hello_world.HelloWorldRequest.greeting', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=71,
)


_HELLOWORLDRESPONSE = _descriptor.Descriptor(
  name='HelloWorldResponse',
  full_name='hello_world.HelloWorldResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='hello_world.HelloWorldResponse.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=107,
)

DESCRIPTOR.message_types_by_name['HelloWorldRequest'] = _HELLOWORLDREQUEST
DESCRIPTOR.message_types_by_name['HelloWorldResponse'] = _HELLOWORLDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloWorldRequest = _reflection.GeneratedProtocolMessageType('HelloWorldRequest', (_message.Message,), dict(
  DESCRIPTOR = _HELLOWORLDREQUEST,
  __module__ = 'hello_world_pb2'
  # @@protoc_insertion_point(class_scope:hello_world.HelloWorldRequest)
  ))
_sym_db.RegisterMessage(HelloWorldRequest)

HelloWorldResponse = _reflection.GeneratedProtocolMessageType('HelloWorldResponse', (_message.Message,), dict(
  DESCRIPTOR = _HELLOWORLDRESPONSE,
  __module__ = 'hello_world_pb2'
  # @@protoc_insertion_point(class_scope:hello_world.HelloWorldResponse)
  ))
_sym_db.RegisterMessage(HelloWorldResponse)



_HELLOWORLDGREETER = _descriptor.ServiceDescriptor(
  name='HelloWorldGreeter',
  full_name='hello_world.HelloWorldGreeter',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=109,
  serialized_end=205,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='hello_world.HelloWorldGreeter.SayHello',
    index=0,
    containing_service=None,
    input_type=_HELLOWORLDREQUEST,
    output_type=_HELLOWORLDRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HELLOWORLDGREETER)

DESCRIPTOR.services_by_name['HelloWorldGreeter'] = _HELLOWORLDGREETER

# @@protoc_insertion_point(module_scope)
